code --install-extension AndersEAndersen.html-class-suggestions
code --install-extension anseki.vscode-color
code --install-extension christian-kohler.path-intellisense
code --install-extension ckolkman.vscode-postgres
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension ecmel.vscode-html-css
code --install-extension Equinusocio.vsc-material-theme
code --install-extension formulahendry.auto-close-tag
code --install-extension mechatroner.rainbow-csv
code --install-extension MS-CEINTL.vscode-language-pack-pt-BR
code --install-extension ms-python.python
code --install-extension ms-vscode.csharp
code --install-extension msjsdiag.debugger-for-chrome
code --install-extension PKief.material-icon-theme
code --install-extension redhat.java
code --install-extension shinnn.stylelint
code --install-extension tjlastnumber.material-last
code --install-extension vincaslt.highlight-matching-tag
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscode-icons-team.vscode-icons
code --install-extension yzhang.markdown-all-in-one
code --install-extension Zignd.html-css-class-completion
